default: &default
  adapter: postgresql
  encoding: unicode
  user: colton
  password: cookie12
  pool: 25
  timeout: 5000

development:
  <<: *default
  database: cer_dev

test:
  <<: *default
  database: cer_test

production:
  <<: *default
  database: cer_dev
